### ISSUE TITLE
Editor field now white when "Mocha" is enabled after updating to 3.2.2

### ISSUE THREAD

**Issue by matteodev8** [catppuccin/jetbrains#115] opened 2023-12-08 16:23 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

The code field turned white after updating and using the Mocha variant, the rest of the UI is unaffected. 

### Attach screenshots.

![image](https://github.com/catppuccin/jetbrains/assets/59450459/a9eff3b1-e369-47e2-8130-ad6b99429058)

![image](https://github.com/catppuccin/jetbrains/assets/59450459/ea2c25b3-94ba-4a48-8cef-eb8396cc9d7c)

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2023.3 (Ultimate Edition)

**Comment by sgoudham** [comment] 2023-12-08 17:22
Hey 👋 

I can see that you've ticked the box that says you've checked the pinned issue (#97) but are you sure that you checked it? This issue is covered there and a duplicate of others (#105, #96)

In any case, please see https://github.com/catppuccin/jetbrains/issues/87#issuecomment-1743872629

Unfortunately, I'm not really sure why this happens.

**Closed by sgoudham** 2023-12-08 17:22 UTC
Labels: bug
