### ISSUE TITLE
Missing color for the search result highlights on scrollbar

### ISSUE THREAD

**Issue by EgorBakanov** [catppuccin/jetbrains#174] opened 2024-10-10 06:51 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

Scrollbar does not display any highlights for search results in all Catppuccin theme flavours

### Attach screenshots.

*Catppuccin Mocha*
![Catppuccin Mocha](https://github.com/user-attachments/assets/272cda32-8dce-4d72-964a-27367ffa8393)

*Dark*
![Dark](https://github.com/user-attachments/assets/66f6818d-b258-4b29-a478-70714139731a)

### What IDE(s) are you seeing the problem on?

JetBrains Rider 2024.2.6

**Comment by kjnsn** [comment] 2024-10-10 08:11
This is a dupe of #166

**Comment by EgorBakanov** [comment] 2024-10-15 08:13
It turns out that this requires setting a separate `ERROR_STRIPE_COLOR` attribute to work:

https://github.com/dracula/jetbrains/blob/589a2b5616ba31b8a36bf38935529ae868732881/src/main/resources/themes/Dracula.xml#L1771-L1777

**Comment by sgoudham** [comment] 2024-10-27 22:56
Happy to accept a PR for this, I don't have the time to look at this repository at the minute.

**Closed** 2024-11-13 17:43 UTC
Labels: bug, help wanted, good first issue
