### ISSUE TITLE
Keyboard shortcut doesn't work in the commit panel

### ISSUE THREAD

**Issue by jonathanhar** [catppuccin/jetbrains#189] opened 2024-11-28 10:30 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

When you make changes and hit `Ctrl+K`, you can't use `Alt+P` to push.

### What IDE(s) are you seeing the problem on?

PyCharm 2024.3 Build #JBC-243.21565.199, built on November 13, 2024 Licensed to Fine / Jonathan Harel Subscription is active until May 29, 2025. Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9) VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Toolkit: sun.awt.windows.WToolkit Windows 11.0 Controller in Remote Development GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation Memory: 1500M Cores: 20 Registry:   ide.experimental.ui=true   i18n.locale=   rdclient.backend.actionHandlers=false Non-Bundled Plugins:   com.intellij.plugins.github.colorscheme (243.21565.122)   ru.adelf.idea.dotenv (2024.3)   com.github.catppuccin.jetbrains (3.4.0)   com.intellij.plugins.monokai.colorscheme (243.21565.122)   some.awesome (1.16)   com.intellij.plugins.twilight.colorscheme (243.21565.122)   com.jetbrains.darkPurpleTheme (1.3)   com.intellij.plugins.warmneon.colorscheme (243.21565.122)   Key Promoter X (2024.2.2)

**Comment by sgoudham** [comment] 2024-11-28 12:25
Hey 👋,

This is a colourscheme plugin and it should absolutely no way impact any keymaps configured in the IDE. I'm going to close this issue as not planned as I would be _absolutely flabberghasted_ if this was being caused by Catppuccin.

You should report this to JetBrains themselves in their [issue tracker](https://youtrack.jetbrains.com/).

**Closed by sgoudham** 2024-11-28 12:25 UTC
Labels: bug
