### ISSUE TITLE
2024.3 performance issues caused by Catppuccin

### ISSUE THREAD

**Issue by SupianIDz** [catppuccin/jetbrains#191] opened 2024-12-17 08:35 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

When using the Catppuccin (latte) theme, the action is not as responsive as when using the default theme, and sometimes can even cause a crash.

As can be seen from the attached video, when I open a pop up to do something, the cursor experiences severe lag, whether using the keyboard arrow keys or using the mouse.

### Attach screenshots.

Uploading Screen Recording 2024-12-17 at 16.26.13.mp4…

### What IDE(s) are you seeing the problem on?

PhpStorm 2024.3 & IDEA 2024.3

### Any additional comments?

This also happens in Intellij IDEA on the latest stable version.

**Comment by sgoudham** [comment] 2024-12-17 08:39
Duplicate of #190

**Closed by sgoudham** 2024-12-17 08:39 UTC
Labels: bug
