### ISSUE TITLE
Readability issue of popup when invoking Go to implementations action

### ISSUE THREAD

**Issue by dodalovicgran** [catppuccin/jetbrains#44] opened 2022-12-23 09:49 UTC
When I invoke the action, i get something like following:
![image](https://user-images.githubusercontent.com/116893230/209313400-1988ad6b-a029-40d3-b68a-9b82117c85a6.png)

Maybe it can be made somewhat more readable. 

wdyt?

Thanks

**Comment by nekowinston** [comment] 2022-12-23 09:55
Hi there 👋 

I think this is a duplicate of #39 - it looks like the same UI element would apply here.

**Comment by sgoudham** [comment] 2022-12-27 22:39
I agree with @nekowinston and am closing it as a duplicate.

**Closed by sgoudham** 2022-12-27 22:39 UTC
Labels: duplicate
