### ISSUE TITLE
Pastel colors are missing in some places

### ISSUE THREAD

**Issue by mudkipdev** [catppuccin/jetbrains#122] opened 2024-02-14 07:45 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

In the file menu (when selected):
![image](https://github.com/catppuccin/jetbrains/assets/86132148/dd9a75ba-d279-480f-9429-50e1e22d39d8)

In autocomplete:
![image](https://github.com/catppuccin/jetbrains/assets/86132148/7fbb9521-6901-48c7-bc92-fcb658ef1541)

In search (when selected):
![image](https://github.com/catppuccin/jetbrains/assets/86132148/77830e4c-caf0-4d69-b7be-1a12b3af2803)

The lighter pastel colored icons are expected, but you can see the darker colored icons match this screenshot from the default Darcula theme.
![image](https://github.com/catppuccin/jetbrains/assets/86132148/5dd1fd80-7daf-4ff8-ad33-8755af7ef144)

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2023.3.2 (Community Edition)

**Comment by sgoudham** [comment] 2024-02-14 14:34
Hey 👋, I'm unable to reproduce these issues on **IntelliJ IDEA 2023.2.1 (Ultimate Edition)** using the **New UI (Compact)**

<details>
<summary>Screenshots</summary>

Search:
![image](https://github.com/catppuccin/jetbrains/assets/58985301/3f8e1504-f76f-4a85-b797-1b32e0eadcc9)

Autocomplete:
![image](https://github.com/catppuccin/jetbrains/assets/58985301/191302dd-18f0-40cd-b553-73b4c1938ada)

</details>

I also checked when turning off the new UI, and they seem consistent to me:

<details>
<summary>Screenshots</summary>

Search:
![image](https://github.com/catppuccin/jetbrains/assets/58985301/641e9a35-6324-4304-8825-55832f9e4596)

Autcomplete:
![image](https://github.com/catppuccin/jetbrains/assets/58985301/7d4ab12e-bcda-43bd-aae4-a61950b147be)

</details>

I really have no idea why IDE is reverting back to darcula icons 🤔 
Based on our conversation in discord, I'm assuming you've tried uninstalling/reinstalling? clearing cache? downgrading your IDE?

**Comment by sgoudham** [comment] 2024-04-06 01:23
Closing as issue has gone a month without reply from author and I'm unable to reproduce the issue.

**Closed by sgoudham** 2024-04-06 01:23 UTC
Labels: bug, waiting for author, unable to reproduce

**Comment by mudkipdev** [comment] 2024-09-14 01:37
Issue is persistent on IntelliJ IDEA 2024.2.1 (Community Edition)
Build #IC-242.21829.142, built on August 28, 2024
Theme version: v3.3.3
