### ISSUE TITLE
Color Scheme does not take effect 

### ISSUE THREAD

**Issue by trunghieu99tt** [catppuccin/jetbrains#45] opened 2022-12-25 14:49 UTC
I recently installed catppuccin, but the color scheme does not appear to be working. The texts are not highlighted, as shown in the image below.
Update: Some areas of my file have the color scheme working, but others do not; I'm not sure what's causing this issue.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/37579106/209472446-60ee9a04-cb5c-4b4e-ad83-fb690f9140e4.png">

**Comment by sgoudham** [comment] 2022-12-27 23:02
Hey :wave:, I think I've managed to figure out what's wrong here. 

Have you marked your code as `src` within JetBrains? JetBrains actively avoids highlighting all the code when it cannot determine certain information.

I have replicated your issue below, notice how the `src` folder on the left is not blue (not marked as source root)
![image](https://user-images.githubusercontent.com/58985301/209734718-cd8d9b35-aad5-451a-8056-1e3377af0f4e.png)

The below screenshot is with the `src` folder marked as sources root and highlights are working as intended.
![image](https://user-images.githubusercontent.com/58985301/209734760-ef018b4c-e465-4897-8c8e-9c4194e841e5.png)

Can you let me know if the above fixes your problem?

**Comment by nekowinston** [comment] 2023-01-28 17:44
Closing this because of inactivity.

**Closed by nekowinston** 2023-01-28 17:44 UTC
Labels: waiting for author
