### ISSUE TITLE
Accent Colour

### ISSUE THREAD

**Issue by brandao07** [catppuccin/jetbrains#86] opened 2023-09-23 17:11 UTC
In the VSCode extension it is possible to change the default value of the accent colour by using:

 `"catppuccin.accentColor": "blue",`

I wonder if there's something like that too for the plugin. 

Thanks.

**Comment by nekowinston** [comment] 2023-09-23 17:12
Hey there 👋 
This is a duplicate of https://github.com/catppuccin/jetbrains/issues/58, please see that issue for the previous discussion / what needs to be done.

**Closed by nekowinston** 2023-09-23 17:12 UTC
